version: "3.4"
services:
  vite_docker:
    build: .
    container_name: vite_docker
    ports:
      - "5173:5173"
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
