version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: spc_app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - spc-network
        depends_on:
            - mysql
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - REDIS_HOST=redis
            - REDIS_PORT=6379

    web:
        image: nginx:alpine
        container_name: spc_web
        volumes:
            - .:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - spc-network
        depends_on:
            - app
        ports:
            - "80:80"
        restart: unless-stopped

    mysql:
        image: mysql:8.0
        container_name: spc_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - spc-network
        ports:
            - "3306:3306"

    redis:
        image: redis:alpine
        container_name: spc_redis
        networks:
            - spc-network
        ports:
            - "6379:6379"

volumes:
    mysql-data:

networks:
    spc-network:
        driver: bridge
